### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by karthink** [SqrtMinusOne/eshell-atuin#1]
@SqrtMinusOne Thanks for writing eshell-atuin.  Incidentally, I was trying to write the exact same functionality this week, but using a dynamic completion table (and thus no cache).  It wasn't going well, now I don't need to bother!

While we're here, thanks for your emacs-i3-integration code as well!  I've been using it for quite some time now.

I did have an issue to report, but I'll do it separately -- feel free to close this one.

**Comment by SqrtMinusOne** [comment]
Thanks <3  Dynamic completion mystifies me a bit, to be honest. Although this approach would work with `relativetime`, unlike mine.

Also, it's funny that I switched to EXWM a few months after writing that i3 integration post, but I guess it still works.

**Comment by karthink** [comment]
> Also, it's funny that I switched to EXWM a few months after writing that i3 integration post, but I guess it still works.

As I remember, I ended up modifying it and using socket-based IPC so I could use it with qtile as well.
