### ISSUE TITLE
How to switch between directory / host / session / global mode?

### ISSUE THREAD

**Issue by julian-hoch** [SqrtMinusOne/eshell-atuin#8]
It seems that `eshell-atuin-history` uses the default atuin mode (in my case 'directory'). Is there a way to use the other modes?

**Comment by SqrtMinusOne** [comment]
Thanks, I wasn't aware about this option, it's actually super useful.

I've added a variable called `eshell-atuin-filter-mode` and the ability to swtich filter modes at runtime with `C-u 0 ...` ... `C-u 3 ...` (see the [README](https://github.com/SqrtMinusOne/eshell-atuin?tab=readme-ov-file#filter-mode)). It seems like doing something more ergonomic would require using functionality from a particular completion system.

I've even managed to make "host" work with TRAMP, but not "directory", unfortunately. Maybe I'll contribute something upstream for the latter.
